### ISSUE TITLE
[molenbike.coopcycle.org] Error on cart validation

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#259]
```
2018/03/06 21:04:28 [error] 16630#16630: *163605 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getGeo() on null in /var/www/molenbike/releases/77/src/AppBundle/Validator/Constraints/CartValidator.php:38
Stack trace:
#0 /var/www/molenbike/releases/77/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php(829): AppBundle\Validator\Constraints\CartValidator->validate(Object(AppBundle\Entity\Cart\Cart), Object(AppBundle\Validator\Constraints\Cart))
#1 /var/www/molenbike/releases/77/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php(542): Symfony\Component\Validator\Validator\RecursiveContextualValidator->validateInGroup(Object(AppBundle\Entity\Cart\Cart), '000000003df9592...', Object(Symfony\Component\Validator\Mapping\ClassMetadata), 'Default', Object(Symfony\Component\Validator\Context\ExecutionContext))
#2 /var/www/molenbike/releases/77/vendor/symfony/symfony/src/Symfony/Component/Validator/V" while reading response header from upstream, client: 176.158.30.201, server: molenbike.coopcycle.org, request: "POST /fr/restaurant/8/cart HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.1-fpm.sock:", host: "molenbike.coopcycle.org", referrer: "https://molenbike.coopcycle.org/fr/restaurant/8-lepo-belge"
```

**Comment by alexsegura** [comment]
Fixed in ed09bf0a42428b3c3150514144a50245c3504233
