### ISSUE TITLE
When uploading a csv on the dashboard, it runs forever and never actually loads

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3438]
**Describe the bug**
When I upload a csv file on the dashboard, the little circle runs forever and the file never actually loads. It does this with files that have an "assign" column.

**To Reproduce**
1. Uplaod the csv file and wait for the magic to happen

**Expected behavior**
The tasks should get listed in the unassigned courriers' tasks' lists.

**Screenshots**
![image](https://user-images.githubusercontent.com/44605344/195803088-49508451-a6be-4549-bd55-61c8e65242a6.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Professionnel
 - Browser : Chrome

**Additional context**
I'll send you the example of a csv file with which it causes this issue.

**Comment by alexsegura** [comment]
The underlying error is the following:

> Unable to find "AppBundle\Entity\User" entity identifier associated with the UnitOfWork

```
Doctrine\ORM\EntityNotFoundException: Unable to find "AppBundle\Entity\User" entity identifier associated with the UnitOfWork
#31 /vendor/doctrine/orm/lib/Doctrine/ORM/EntityNotFoundException.php(43): Doctrine\ORM\EntityNotFoundException::noIdentifierFound
#30 /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(3081): Doctrine\ORM\UnitOfWork::getEntityIdentifier
#29 /vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(693): Doctrine\ORM\Persisters\Entity\BasicEntityPersister::prepareUpdateData
#28 /vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(730): Doctrine\ORM\Persisters\Entity\BasicEntityPersister::prepareInsertData
#27 /vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(268): Doctrine\ORM\Persisters\Entity\BasicEntityPersister::executeInserts
#26 /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1129): Doctrine\ORM\UnitOfWork::executeInserts
#25 /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(430): Doctrine\ORM\UnitOfWork::commit
#24 /vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(403): Doctrine\ORM\EntityManager::flush
#23 /var/cache/prod/ContainerRxm6Cjp/EntityManager_9a5be93.php(90): ContainerRxm6Cjp\EntityManager_9a5be93::flush
#22 /src/MessageHandler/ImportTasksHandler.php(127): AppBundle\MessageHandler\ImportTasksHandler::__invoke
#21 /vendor/symfony/symfony/src/Symfony/Component/Messenger/Middleware/HandleMessageMiddleware.php(95): Symfony\Component\Messenger\Middleware\HandleMessageMiddleware::handle
#20 /vendor/symfony/symfony/src/Symfony/Component/Messenger/Middleware/SendMessageMiddleware.php(73): Symfony\Component\Messenger\Middleware\SendMessageMiddleware::handle
#19 /vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/Messenger/DoctrineCloseConnectionMiddleware.php(31): Symfony\Bridge\Doctrine\Messenger\DoctrineCloseConnectionMiddleware::handleForManager
#18 /vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/Messenger/AbstractDoctrineMiddleware.php(45): Symfony\Bridge\Doctrine\Messenger\AbstractDoctrineMiddleware::handle
#17 /vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/Messenger/DoctrinePingConnectionMiddleware.php(33): Symfony\Bridge\Doctrine\Messenger\DoctrinePingConnectionMiddleware::handleForManager
#16 /vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/Messenger/AbstractDoctrineMiddleware.php(45): Symfony\Bridge\Doctrine\Messenger\AbstractDoctrineMiddleware::handle
#15 /vendor/symfony/symfony/src/Symfony/Component/Messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\Component\Messenger\Middleware\FailedMessageProcessingMiddleware::handle
#14 /vendor/symfony/symfony/src/Symfony/Component/Messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\Component\Messenger\Middleware\DispatchAfterCurrentBusMiddleware::handle
#13 /vendor/symfony/symfony/src/Symfony/Component/Messenger/Middleware/RejectRedeliveredMessageMiddleware.php(48): Symfony\Component\Messenger\Middleware\RejectRedeliveredMessageMiddleware::handle
#12 /vendor/symfony/symfony/src/Symfony/Component/Messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\Component\Messenger\Middleware\AddBusNameStampMiddleware::handle
#11 /vendor/symfony/symfony/src/Symfony/Component/Messenger/MessageBus.php(77): Symfony\Component\Messenger\MessageBus::dispatch
#10 /vendor/symfony/symfony/src/Symfony/Component/Messenger/RoutableMessageBus.php(54): Symfony\Component\Messenger\RoutableMessageBus::dispatch
#9 /vendor/symfony/symfony/src/Symfony/Component/Messenger/Worker.php(158): Symfony\Component\Messenger\Worker::handleMessage
#8 /vendor/symfony/symfony/src/Symfony/Component/Messenger/Worker.php(107): Symfony\Component\Messenger\Worker::run
#7 /vendor/symfony/symfony/src/Symfony/Component/Messenger/Command/ConsumeMessagesCommand.php(225): Symfony\Component\Messenger\Command\ConsumeMessagesCommand::execute
#6 /vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(298): Symfony\Component\Console\Command\Command::run
#5 /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(1046): Symfony\Component\Console\Application::doRunCommand
#4 /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(96): Symfony\Bundle\FrameworkBundle\Console\Application::doRunCommand
#3 /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(299): Symfony\Component\Console\Application::doRun
#2 /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(82): Symfony\Bundle\FrameworkBundle\Console\Application::doRun
#1 /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(171): Symfony\Component\Console\Application::run
#0 /bin/console(43): null
```

**Comment by ERAMANrepartos** [comment]
Have we done anything about the underlying error? @alexsegura

**Comment by Paul-Eraman-CoopCycle** [comment]
So we have spent a significant amount of time looking into this, and we are having problems finding the error. 

This has never happened to me...how frequent is this for you @rayon9coop ?

**Comment by rayon9coop** [comment]
2 to 3 times a week. In fact, every time we upload a csv with tasks and several couriers assigned to these tasks

**Comment by Paul-Eraman-CoopCycle** [comment]
is this still happening @rayon9coop ?

**Comment by alexsegura** [comment]
Nowhere to be found on Sentry, closing.
