### ISSUE TITLE
Address without geo coordinates causes exception

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#3472]
This error regularly happens on [Sentry](https://sentry.io/organizations/coopcycle/issues/2448273500/?project=5294179&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d). 

It means that `$dropoffAddress->getGeo()` returns NULL in this piece of code. 

https://github.com/coopcycle/coopcycle-web/blob/9a9dcb7fa95798eeb91b966f30c07048013eddd6/src/Service/DeliveryManager.php#L110-L113

It happens in the `restaurant_cart` route, i.e when the address of the cart is updated, or the time slot. 

```
TypeError: AppBundle\Service\Routing\OsrmWithFallback::getDistance(): Argument #2 must be of type AppBundle\Entity\Base\GeoCoordinates, null given, called in /home/coopcycle/.coopcycle/app/releases/9a9dcb7fa95798eeb91b966f30c07048013eddd6/src/Service/DeliveryManager.php on line 112
#18 /src/Service/Routing/OsrmWithFallback.php(38): AppBundle\Service\Routing\OsrmWithFallback::getDistance
#17 /src/Service/DeliveryManager.php(112): AppBundle\Service\DeliveryManager::createFromOrder
#16 /src/Sylius/OrderProcessing/OrderFeeProcessor.php(221): AppBundle\Sylius\OrderProcessing\OrderFeeProcessor::getDelivery
#15 /src/Sylius/OrderProcessing/OrderFeeProcessor.php(65): AppBundle\Sylius\OrderProcessing\OrderFeeProcessor::process
#14 /vendor/sylius/order/Processor/CompositeOrderProcessor.php(41): Sylius\Component\Order\Processor\CompositeOrderProcessor::process
#13 /src/Sylius/OrderProcessing/OrderOptionsFeeProcessor.php(30): AppBundle\Sylius\OrderProcessing\OrderOptionsFeeProcessor::process
#12 /vendor/sylius/order/Processor/CompositeOrderProcessor.php(41): Sylius\Component\Order\Processor\CompositeOrderProcessor::process
#11 /src/Form/Order/CartType.php(117): AppBundle\Form\Order\CartType::AppBundle\Form\Order\{closure}
#10 /vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(230): Symfony\Component\EventDispatcher\EventDispatcher::callListeners
#9 /vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher::dispatch
#8 /vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ImmutableEventDispatcher.php(33): Symfony\Component\EventDispatcher\ImmutableEventDispatcher::dispatch
#7 /vendor/symfony/symfony/src/Symfony/Component/Form/Form.php(654): Symfony\Component\Form\Form::submit
#6 /vendor/sylius/resource-bundle/src/Bundle/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php(107): Sylius\Bundle\ResourceBundle\Form\Extension\HttpFoundation\HttpFoundationRequestHandler::handleRequest
#5 /vendor/symfony/symfony/src/Symfony/Component/Form/Form.php(503): Symfony\Component\Form\Form::handleRequest
#4 /src/Controller/RestaurantController.php(533): AppBundle\Controller\RestaurantController::cartAction
#3 /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(153): Symfony\Component\HttpKernel\HttpKernel::handleRaw
#2 /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel::handle
#1 /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(202): Symfony\Component\HttpKernel\Kernel::handle
#0 /index.php(28): null
```

**Comment by alexsegura** [comment]
To reproduce the conditions of the bug, we need to configure a restaurant with variable amounts, so that it triggers the distance calculation. 

<img width="1125" alt="Capture d’écran 2022-11-10 à 14 28 31" src="https://user-images.githubusercontent.com/1162230/201104157-f658d243-9046-4c74-b16d-ff4a0d078aec.png">
