### ISSUE TITLE
500 Internal Server Error when creating a new Tarification

### ISSUE THREAD

**Issue by En-Roue-Livr** [coopcycle/coopcycle-web#3743]
Scenario that leads to this error message:
- I duplicate our Tarification named "Un seul S/M/L" and name the new Tarification.
- I remove the rules related to zones and modify that related to the first km.
- I click on Enregistrer and get the "500 Internal Server Error" message.
This happened twice. This alternate scenario was successful:
- Duplicate the Tarification and name the new one.
- Modify the rule related to the first km.
- Click on Enregistrer
- Remove the rules related to zones
- Click on Enregistrer

If you create new Tarifications for test purposes, please delete them afterwards, because we can't. Thank you.

**Comment by r0xsh** [comment]
@alexsegura is commit https://github.com/coopcycle/coopcycle-web/commit/335b0daf766f43b654f370951d94176da62e9feb fixes this issue ?

**Comment by alexsegura** [comment]
@r0xsh no, 335b0daf766f43b654f370951d94176da62e9feb doesn't fix this issue, it just fails silently when trying to create a delivery via the API, and not being able to calculate the price. The error seems to be in the rule itself, check on Sentry.

**Comment by alexsegura** [comment]
This is the actual error

> Doctrine\ORM\ORMInvalidArgumentException
Detached entity AppBundle\Entity\Delivery\PricingRule@3224 cannot be removed

```
Doctrine\ORM\ORMInvalidArgumentException: Detached entity AppBundle\Entity\Delivery\PricingRule@3224 cannot be removed
#10 /vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php(175): Doctrine\ORM\ORMInvalidArgumentException::detachedEntityCannot
#9 /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1909): Doctrine\ORM\UnitOfWork::doRemove
#8 /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1860): Doctrine\ORM\UnitOfWork::remove
#7 /vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(689): Doctrine\ORM\EntityManager::remove
#6 /var/cache/prod/ContainerWvxBKYg/EntityManager_9a5be93.php(125): ContainerWvxBKYg\EntityManager_9a5be93::remove
#5 /src/Controller/AdminController.php(994): AppBundle\Controller\AdminController::renderPricingRuleSetForm
#4 /src/Controller/AdminController.php(1058): AppBundle\Controller\AdminController::duplicatePricingRuleSetAction
#3 /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(163): Symfony\Component\HttpKernel\HttpKernel::handleRaw
#2 /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel::handle
#1 /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(202): Symfony\Component\HttpKernel\Kernel::handle
#0 /index.php(28): null
```

**Comment by r0xsh** [comment]
Oh i got confused by the misleading issue title. It's related the soft-delete entities topic

**Comment by Paul-Eraman-CoopCycle** [comment]
is this still an issue @alexsegura ?

**Comment by alexsegura** [comment]
I see it still happening yes.

**Comment by Paul-Eraman-CoopCycle** [comment]
can you query how often it happens @alexsegura as a % of total price rule creation interactions?
