### ISSUE TITLE
the site no load css 

### ISSUE THREAD

**Issue by mesayuda** [coopcycle/coopcycle-web#503]
please help, i install de software but no load any css, images o style.

![captura de pantalla -2018-11-11 17-51-22](https://user-images.githubusercontent.com/44527666/48319549-62a03600-e5dd-11e8-9cec-0ca76f0ba65c.png)

any idea?

thanks for you help

**Comment by freelibre** [comment]
May be it's the same issue as this one:
https://github.com/coopcycle/coopcycle-web/issues/436#issuecomment-425638834
you may need to rebuild node-sass, see the comments associated.

**Comment by mesayuda** [comment]
hi @freelibre 

i follow this order and no works, when i execute the order docker-compose up i see this in the log:
Error: Plugin/Preset files are not allowed to export objects, only functions. In /srv/coopcycle/node_modules/babel-preset-react/lib/index.js
webpack_1_178406eb27d1 |     at createDescriptor (/srv/coopcycle/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
webpack_1_178406eb27d1 |     at items.map (/srv/coopcycle/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
webpack_1_178406eb27d1 |     at Array.map (<anonymous>)
webpack_1_178406eb27d1 |     at createDescriptors (/srv/coopcycle/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
webpack_1_178406eb27d1 |     at createPresetDescriptors (/srv/coopcycle/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
webpack_1_178406eb27d1 |     at presets (/srv/coopcycle/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
webpack_1_178406eb27d1 |     at mergeChainOpts (/srv/coopcycle/node_modules/@babel/core/lib/config/config-chain.js:320:26)
webpack_1_178406eb27d1 |     at /srv/coopcycle/node_modules/@babel/core/lib/config/config-chain.js:283:7
webpack_1_178406eb27d1 |     at buildRootChain (/srv/coopcycle/node_modules/@babel/core/lib/config/config-chain.js:120:22)
webpack_1_178406eb27d1 |     at loadPrivatePartialConfig (/srv/coopcycle/node_modules/@babel/core/lib/config/partial.js:85:55)
coopcycle-web_webpack_1_178406eb27d1 exited with code 1

i think that babel no works fine and webpack no start.

you can help me with this?

thanks

**Comment by freelibre** [comment]
Could you please precise what you mean by 

> i follow this  order

and could also please share the exact command you've launched and the full logs ?

**Comment by mesayuda** [comment]
> Could you please precise what you mean by
> 
> > i follow this  order
> 
> and could also please share the exact command you've launched and the full logs ?

sure, first, i run this command:

alejandro@mesayuda:~/coopcycle-web$ docker-compose exec webpack npm rebuild node-sass

> node-sass@4.9.3 install /srv/coopcycle/node_modules/node-sass
> node scripts/install.js

node-sass build Binary found at /srv/coopcycle/node_modules/node-sass/vendor/linux_musl-x64-57/binding.node

> node-sass@4.9.3 postinstall /srv/coopcycle/node_modules/node-sass
> node scripts/build.js

Binary found at /srv/coopcycle/node_modules/node-sass/vendor/linux_musl-x64-57/binding.node
Testing binary
Binary is fine
node-sass@4.9.3 /srv/coopcycle/node_modules/node-sass
alejandro@mesayuda:~/coopcycle-web$

it no show errors.

second i run this command: 

alejandro@mesayuda:~/coopcycle-web$ docker-compose up
Starting coopcycle-web_graphite_1_ae0cc09cf716    ... done
Starting coopcycle-web_stripe_mock_1_d41f62dd2551 ... done
Starting coopcycle-web_postgres_1_7b7ac547cd11    ... done
Starting coopcycle-web_redis_1_89c5af17beaf       ... done
Starting coopcycle-web_webpack_1_178406eb27d1     ... done
Starting coopcycle-web_osrm_1_2ddad1958f57        ... done
Starting coopcycle-web_smtp_1_a13448a0060e        ... done
Starting coopcycle-web_grafana_1_ce91b9aa46a8     ... done
Starting coopcycle-web_nodejs_1_db9e3c3f0243      ... done
Starting coopcycle-web_php_1_2a17fee7c13a         ... done
Starting coopcycle-web_nginx_1_610bbe2d677b       ... done
Attaching to coopcycle-web_stripe_mock_1_d41f62dd2551, coopcycle-web_graphite_1_ae0cc09cf716, coopcycle-web_postgres_1_7b7ac547cd11, coopcycle-web_grafana_1_ce91b9aa46a8, coopcycle-web_redis_1_89c5af17beaf, coopcycle-web_osrm_1_2ddad1958f57, coopcycle-web_webpack_1_178406eb27d1, coopcycle-web_php_1_2a17fee7c13a, coopcycle-web_smtp_1_a13448a0060e, coopcycle-web_nodejs_1_db9e3c3f0243, coopcycle-web_nginx_1_610bbe2d677b
stripe_mock_1_d41f62dd2551 | stripe-mock master
stripe_mock_1_d41f62dd2551 | Routing to 172 path(s) and 295 endpoint(s) with 295 validator(s)
stripe_mock_1_d41f62dd2551 | Listening for HTTP on port: 12111
stripe_mock_1_d41f62dd2551 | Listening for HTTPS on port: 12112
graphite_1_ae0cc09cf716 | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
graphite_1_ae0cc09cf716 | *** Running /etc/my_init.d/01_conf_init.sh...
graphite_1_ae0cc09cf716 | *** Running /etc/my_init.d/10_syslog-ng.init...
graphite_1_ae0cc09cf716 | Nov 12 17:30:56 dff35ef25a95 syslog-ng[23]: syslog-ng starting up; version='3.13.2'
graphite_1_ae0cc09cf716 | *** Booting runit daemon...
graphite_1_ae0cc09cf716 | *** Runit started as PID 32
graphite_1_ae0cc09cf716 | Nov 12 17:30:57 dff35ef25a95 cron[44]: (CRON) INFO (pidfile fd = 3)
graphite_1_ae0cc09cf716 | Nov 12 17:30:57 dff35ef25a95 cron[44]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
graphite_1_ae0cc09cf716 | ok: run: nginx: (pid 46) 1s
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Starting Grafana" logger=server version=5.3.2 commit=0d821d0 compiled=2018-10-24T12:06:27+0000
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_DATA=/var/lib/grafana"
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_LOGS=/var/log/grafana"
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
postgres_1_7b7ac547cd11 | LOG:  database system was shut down at 2018-11-12 17:28:44 UTC
postgres_1_7b7ac547cd11 | LOG:  MultiXact member wraparound protections are now enabled
postgres_1_7b7ac547cd11 | LOG:  database system is ready to accept connections
postgres_1_7b7ac547cd11 | LOG:  autovacuum launcher started
redis_1_89c5af17beaf | 1:C 12 Nov 2018 17:31:00.299 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1_89c5af17beaf | 1:C 12 Nov 2018 17:31:00.300 # Redis version=5.0.1, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1_89c5af17beaf | 1:C 12 Nov 2018 17:31:00.300 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1_89c5af17beaf | 1:M 12 Nov 2018 17:31:00.302 * Running mode=standalone, port=6379.
redis_1_89c5af17beaf | 1:M 12 Nov 2018 17:31:00.302 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1_89c5af17beaf | 1:M 12 Nov 2018 17:31:00.302 # Server initialized
redis_1_89c5af17beaf | 1:M 12 Nov 2018 17:31:00.302 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1_89c5af17beaf | 1:M 12 Nov 2018 17:31:00.302 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1_89c5af17beaf | 1:M 12 Nov 2018 17:31:00.302 * DB loaded from disk: 0.000 seconds
redis_1_89c5af17beaf | 1:M 12 Nov 2018 17:31:00.302 * Ready to accept connections
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="App mode production" logger=settings
osrm_1_2ddad1958f57 | [info] starting up engines, v5.16.0
osrm_1_2ddad1958f57 | [info] Threads: 4
osrm_1_2ddad1958f57 | [info] IP address: 0.0.0.0
osrm_1_2ddad1958f57 | [info] IP port: 5000
osrm_1_2ddad1958f57 | [info] load names from: "/data/data.osrm.names"
osrm_1_2ddad1958f57 | [info] set checksum: 1297240911
osrm_1_2ddad1958f57 | [info] set checksum: 1297240911
osrm_1_2ddad1958f57 | [info] set checksum: 1297240911
osrm_1_2ddad1958f57 | [info] set checksum: 1297240911
osrm_1_2ddad1958f57 | [info] set checksum: 1297240911
osrm_1_2ddad1958f57 | [info] set checksum: 1297240911
osrm_1_2ddad1958f57 | [info] set checksum: 1297240911
osrm_1_2ddad1958f57 | [info] set checksum: 1297240911
osrm_1_2ddad1958f57 | [info] http 1.1 compression handled by zlib version 1.2.11
osrm_1_2ddad1958f57 | [info] Listening on: 0.0.0.0:5000
osrm_1_2ddad1958f57 | [info] running and waiting for requests
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Initializing SqlStore" logger=server
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Starting DB migration" logger=migrator
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Initializing HTTPServer" logger=server
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Initializing SearchService" logger=server
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Initializing PluginManager" logger=server
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Starting plugin search" logger=plugins
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Initializing InternalMetricsService" logger=server
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Initializing AlertingService" logger=server
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Initializing CleanUpService" logger=server
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Initializing NotificationService" logger=server
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Initializing ProvisioningService" logger=server
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Initializing RenderingService" logger=server
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Initializing TracingService" logger=server
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="Initializing Stream Manager"
grafana_1_ce91b9aa46a8 | t=2018-11-12T17:30:59+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
php_1_2a17fee7c13a | + ip ro
php_1_2a17fee7c13a | + grep default
php_1_2a17fee7c13a | + cut '-d ' -f 3
php_1_2a17fee7c13a | + export 'DOCKER_BRIDGE_IP=172.18.0.1'
php_1_2a17fee7c13a | + '[' dev '=' prod ]
php_1_2a17fee7c13a | + composer install --prefer-dist --no-progress --no-suggest
php_1_2a17fee7c13a | Loading composer repositories with package information
php_1_2a17fee7c13a | Installing dependencies (including require-dev) from lock file
php_1_2a17fee7c13a | Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
php_1_2a17fee7c13a | Nothing to install or update
php_1_2a17fee7c13a | Generating autoload files
php_1_2a17fee7c13a | ocramius/package-versions:  Generating version class...
php_1_2a17fee7c13a | ocramius/package-versions: ...done generating version class
php_1_2a17fee7c13a | > Incenteev\ParameterHandler\ScriptHandler::buildParameters
php_1_2a17fee7c13a | Updating the "app/config/parameters.yml" file
php_1_2a17fee7c13a | > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
php_1_2a17fee7c13a | > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
smtp_1_a13448a0060e | + sed -ri '
smtp_1_a13448a0060e | 	s/^#?(dc_local_interfaces)=.*/\1='\''[0.0.0.0]:25 ; [::0]:25'\''/;
smtp_1_a13448a0060e | 	s/^#?(dc_other_hostnames)=.*/\1='\'''\''/;
smtp_1_a13448a0060e | 	s/^#?(dc_relay_nets)=.*/\1='\''172.18.0.8\/16'\''/;
smtp_1_a13448a0060e | 	s/^#?(dc_eximconfig_configtype)=.*/\1='\''internet'\''/;
smtp_1_a13448a0060e | ' /etc/exim4/update-exim4.conf.conf
smtp_1_a13448a0060e | + update-exim4.conf -v
smtp_1_a13448a0060e | using non-split configuration scheme from /etc/exim4/exim4.conf.template
smtp_1_a13448a0060e |     1 LOG: MAIN
smtp_1_a13448a0060e |     1   exim 4.84_2 daemon started: pid=1, -q15m, listening for SMTP on port 25 (IPv6 and IPv4)
php_1_2a17fee7c13a | 
php_1_2a17fee7c13a |  // Clearing the cache for the dev environment with debug                       
php_1_2a17fee7c13a |  // true                                                                        
php_1_2a17fee7c13a | 
php_1_2a17fee7c13a |  [OK] Cache for the "dev" environment (debug=true) was successfully cleared.    
php_1_2a17fee7c13a | 
php_1_2a17fee7c13a | > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
php_1_2a17fee7c13a | 
php_1_2a17fee7c13a |  Trying to install assets as relative symbolic links.
php_1_2a17fee7c13a | 
php_1_2a17fee7c13a |  --- -------------------- ------------------ 
php_1_2a17fee7c13a |       Bundle               Method / Error    
php_1_2a17fee7c13a |  --- -------------------- ------------------ 
php_1_2a17fee7c13a |   ✔   ApiPlatformBundle    relative symlink  
php_1_2a17fee7c13a |   ✔   CraueConfigBundle    relative symlink  
php_1_2a17fee7c13a |   ✔   FOSJsRoutingBundle   relative symlink  
php_1_2a17fee7c13a |  --- -------------------- ------------------ 
php_1_2a17fee7c13a | 
php_1_2a17fee7c13a |  [OK] All assets were successfully installed.                                   
php_1_2a17fee7c13a | 
php_1_2a17fee7c13a | > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
php_1_2a17fee7c13a | > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget
php_1_2a17fee7c13a | + php bin/console doctrine:database:create --if-not-exists '--env=dev'
php_1_2a17fee7c13a | Database "coopcycle" for connection named default already exists. Skipped.
php_1_2a17fee7c13a | + php bin/console doctrine:query:sql 'CREATE EXTENSION IF NOT EXISTS postgis' '--env=dev'
php_1_2a17fee7c13a | int(0)
php_1_2a17fee7c13a | + php bin/console doctrine:query:sql 'CREATE EXTENSION IF NOT EXISTS postgis_topology' '--env=dev'
php_1_2a17fee7c13a | int(0)
php_1_2a17fee7c13a | + php bin/console doctrine:database:create --if-not-exists '--env=test'
php_1_2a17fee7c13a | Database "coopcycle_test" for connection named default already exists. Skipped.
php_1_2a17fee7c13a | + php bin/console doctrine:query:sql 'CREATE EXTENSION IF NOT EXISTS postgis' '--env=test'
php_1_2a17fee7c13a | int(0)
php_1_2a17fee7c13a | + php bin/console doctrine:query:sql 'CREATE EXTENSION IF NOT EXISTS postgis_topology' '--env=test'
php_1_2a17fee7c13a | int(0)
php_1_2a17fee7c13a | + chown -R www-data var/cache
php_1_2a17fee7c13a | + chown -R www-data var/logs
php_1_2a17fee7c13a | chown: var/logs/.gitkeep: Operation not permitted
php_1_2a17fee7c13a | chown: var/logs: Operation not permitted
php_1_2a17fee7c13a | chown: var/logs: Operation not permitted
php_1_2a17fee7c13a | + exec php-fpm
php_1_2a17fee7c13a | [12-Nov-2018 17:31:18] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
php_1_2a17fee7c13a | [12-Nov-2018 17:31:18] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
php_1_2a17fee7c13a | [12-Nov-2018 17:31:18] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
php_1_2a17fee7c13a | [12-Nov-2018 17:31:18] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
php_1_2a17fee7c13a | [12-Nov-2018 17:31:18] NOTICE: fpm is running, pid 1
php_1_2a17fee7c13a | [12-Nov-2018 17:31:18] NOTICE: ready to handle connections
webpack_1_178406eb27d1 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
webpack_1_178406eb27d1 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
webpack_1_178406eb27d1 | 
webpack_1_178406eb27d1 | audited 16325 packages in 28.371s
webpack_1_178406eb27d1 | found 0 vulnerabilities
webpack_1_178406eb27d1 | 
nodejs_1_db9e3c3f0243 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
nodejs_1_db9e3c3f0243 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
nodejs_1_db9e3c3f0243 | 
webpack_1_178406eb27d1 | /srv/coopcycle/node_modules/@babel/core/lib/config/config-descriptors.js:178
webpack_1_178406eb27d1 |     throw new Error(`Plugin/Preset files are not allowed to export objects, only functions. In ${filepath}`);
webpack_1_178406eb27d1 |     ^
webpack_1_178406eb27d1 | 
webpack_1_178406eb27d1 | Error: Plugin/Preset files are not allowed to export objects, only functions. In /srv/coopcycle/node_modules/babel-preset-react/lib/index.js
webpack_1_178406eb27d1 |     at createDescriptor (/srv/coopcycle/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
webpack_1_178406eb27d1 |     at items.map (/srv/coopcycle/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
webpack_1_178406eb27d1 |     at Array.map (<anonymous>)
webpack_1_178406eb27d1 |     at createDescriptors (/srv/coopcycle/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
webpack_1_178406eb27d1 |     at createPresetDescriptors (/srv/coopcycle/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
webpack_1_178406eb27d1 |     at presets (/srv/coopcycle/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
webpack_1_178406eb27d1 |     at mergeChainOpts (/srv/coopcycle/node_modules/@babel/core/lib/config/config-chain.js:320:26)
webpack_1_178406eb27d1 |     at /srv/coopcycle/node_modules/@babel/core/lib/config/config-chain.js:283:7
webpack_1_178406eb27d1 |     at buildRootChain (/srv/coopcycle/node_modules/@babel/core/lib/config/config-chain.js:120:22)
webpack_1_178406eb27d1 |     at loadPrivatePartialConfig (/srv/coopcycle/node_modules/@babel/core/lib/config/partial.js:85:55)
nodejs_1_db9e3c3f0243 | audited 16325 packages in 27.587s
nodejs_1_db9e3c3f0243 | found 0 vulnerabilities
nodejs_1_db9e3c3f0243 | 
nodejs_1_db9e3c3f0243 | 2018-11-12T17:31:33: PM2 log: Launching in no daemon mode
nodejs_1_db9e3c3f0243 | 2018-11-12T17:31:34: PM2 log: Config file : config_dev.yml
nodejs_1_db9e3c3f0243 | 2018-11-12T17:31:34: PM2 log: [Watch] Start watching coopcycle-dispatch-default
nodejs_1_db9e3c3f0243 | 2018-11-12T17:31:34: PM2 log: App [coopcycle-dispatch-default:0] starting in -fork mode-
nodejs_1_db9e3c3f0243 | 2018-11-12T17:31:34: PM2 log: [Watch] Start watching coopcycle-tracking-default
nodejs_1_db9e3c3f0243 | 2018-11-12T17:31:34: PM2 log: App [coopcycle-tracking-default:1] starting in -fork mode-
nodejs_1_db9e3c3f0243 | 2018-11-12T17:31:34: PM2 log: App [coopcycle-dispatch-default:0] online
nodejs_1_db9e3c3f0243 | 2018-11-12T17:31:34: PM2 log: App [coopcycle-tracking-default:1] online
coopcycle-web_webpack_1_178406eb27d1 exited with code 1
nodejs_1_db9e3c3f0243 | ------------------------
nodejs_1_db9e3c3f0243 | - STARTING DISPATCH V2 -
nodejs_1_db9e3c3f0243 | ------------------------
nodejs_1_db9e3c3f0243 | NODE_ENV = development
nodejs_1_db9e3c3f0243 | PORT = 8000
nodejs_1_db9e3c3f0243 | ---------------------
nodejs_1_db9e3c3f0243 | - STARTING TRACKING -
nodejs_1_db9e3c3f0243 | ---------------------
nodejs_1_db9e3c3f0243 | NODE_ENV = development
nodejs_1_db9e3c3f0243 | PORT = 8001
nodejs_1_db9e3c3f0243 | Mon, 12 Nov 2018 17:31:35 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
php_1_2a17fee7c13a | 172.18.0.12 -  12/Nov/2018:17:31:43 +0000 "GET /app_dev.php" 302
php_1_2a17fee7c13a | 172.18.0.12 -  12/Nov/2018:17:31:45 +0000 "GET /app_dev.php" 200
php_1_2a17fee7c13a | 172.18.0.12 -  12/Nov/2018:17:31:46 +0000 "GET /app_dev.php" 200
php_1_2a17fee7c13a | 172.18.0.12 -  12/Nov/2018:17:31:46 +0000 "GET /app_dev.php" 200
php_1_2a17fee7c13a | 172.18.0.12 -  12/Nov/2018:17:31:46 +0000 "GET /app_dev.php" 200
php_1_2a17fee7c13a | 172.18.0.12 -  12/Nov/2018:17:31:47 +0000 "GET /app_dev.php" 200

thanks for you help

**Comment by freelibre** [comment]
I don't reproduce the issue. May be remove all your installation and try a new install.
Here are the commands you could use to remove your installation:
```
docker ps -a -q | xargs docker stop
docker ps -a -q | xargs docker rm
docker rmi $(docker images -q)
docker volume rm $(docker volume list)
docker network rm $(docker network list)
sudo \rm -rf coopcycle-web
```

**Comment by mike1573** [comment]
I have the same issue, fresh install and reinstall of OS, Docker and Application. Problem occurs each time.
Ubuntu 16.04
Docker 18.09.0
Docker-compose 1.18.0

**Comment by mesayuda** [comment]
I have formatted my computer and installed docker from scratch and still the error persists, I see that the problem is with babel and that is why the webpack ends with error 1, could you please help us with this problem? thank you

**Comment by freelibre** [comment]
So it seems you did not try this:
https://github.com/coopcycle/coopcycle-web/issues/436#issuecomment-425654688
There was new commits in master today may be if the above solution doesn't work `git pull` and try again.

**Comment by mesayuda** [comment]
> Hi @freelibre ....I did the step in #436 but it did not work. These are my steps;
> 
> 1. New VirtualBox VM running Fedora 28, install make
> 2. git clone repository
> 3. Do the permission steps as per readme
> 4. add "RUN npm rebuild node-sass" to the webpack Dockerfile as per your last comment on Sep 29 in #436
> 5. cd coopcycle-web, make install
> 6. docker-compose up
> 
> Same issue. Am I missing something?

i not run nmp rebuild and the software works fine.

**Comment by mike1573** [comment]
Hi @mesayuda, I don't see what changed in your setup to make it work. Are you saying you just installed as normal without doing the step in #436 and it now works? I just tried that again on a new VM box with the steps above removing step 4 and same result.

Let me know what changes you did if any or your setup so that I can replicated it.
Thanks

**Comment by freelibre** [comment]
I guess you can close the issue then.
If you want to create a co_op you should explain your project I think to this email: contact@coopcycle.org
