### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#689]
Some Cypress tests are still flaky

```
1) Checkout homepage search with vague address:
     CypressError: Timed out retrying: Expected to find element: 'ul[role="listbox"] li', but never found it. Queried from element: <div.ReactModal__Content.ReactModal__Content--after-open.ReactModal__Content--enter-address>
      at Object.cypressErr (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:85348:11)
      at Object.throwErr (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:85303:18)
      at Object.throwErrByPath (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:85335:17)
      at retry (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:77321:16)
      at onFailFn (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:68422:16)
      at tryCatcher (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:118962:23)
      at Promise._settlePromiseFromHandler (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:116898:31)
      at Promise._settlePromise (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:116955:18)
      at Promise._settlePromise0 (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:117000:10)
      at Promise._settlePromises (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:117075:18)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:113687:16)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:113697:10)
      at Async.drainQueues (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:113571:14)
      at <anonymous>
```

```
1) Delivery create delivery:
     CypressError: Timed out retrying: cy.click() failed because this element is not visible:
<div>23 Aven...</div>
This element '<div>' is not visible because it has an effective width and height of: '0 x 0' pixels.
Fix this problem, or use {force: true} to disable error checking.
https://on.cypress.io/element-cannot-be-interacted-with
      at Object.cypressErr (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:85348:11)
      at Object.throwErr (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:85303:18)
      at Object.throwErrByPath (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:85335:17)
      at Object.retry (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:77321:16)
      at retryActionability (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:68070:19)
      at tryCatcher (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:118962:23)
      at Function.Promise.attempt.Promise.try (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:116237:29)
      at tryFn (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:77770:21)
      at whenStable (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:77805:12)
      at http://test.coopcycle.org/__cypress/runner/cypress_runner.js:77364:16
      at tryCatcher (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:118962:23)
      at Promise._settlePromiseFromHandler (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:116898:31)
      at Promise._settlePromise (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:116955:18)
      at Promise._settlePromise0 (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:117000:10)
      at Promise._settlePromises (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:117079:18)
      at Promise._fulfill (http://test.coopcycle.org/__cypress/runner/cypress_runner.js:117024:18)
```

**Comment by alexsegura** [comment]
Now tests are quite stable
